jobs:
  - name: repo-manifest3
    type: manifest
    steps:
      - GET: repo-img1
      - GET: repo-img2
      - GET: repo-img3
      - GET: repo-params1
      - GET: repo-dopts1
      - GET: repo-replicas1
      
  - name: repo-ecsdeploy
    type: ecsDeploy
    steps:
      - GET: repo-manifest3
      - GET: repo-ecscluster1
      
  #- name: multimanifest-dcldeploy
   # type: dclDeploy
    #steps:
     # - GET: repo-manifest
      #- GET: repo-manifest2
      #- GET: repo-dclcluster
