jobs:
  - name: vr-man1
    type: manifest
    steps:
      - GET: vr-img2
      
  - name: vr-man2
    type: manifest
    steps:
      - GET: vr-img1
      
  - name: vr-release1
    type: release
    options:
      action: minor
    steps:
      - GET: vr-version
      - GET: vr-man2
      - GET: vr-man1
      
#  - name: vr-tpdeploy
 #   type: tripubDeploy
  #  steps:
   #   - GET: vr-man1
    #  - GET: vr-tpcluster
  
