jobs:
  - name: tri-mf11
    type: manifest
    steps:
      - GET: tp-imgenv
      - GET: tp-params11
      - GET: tp-replica12
      
  - name: tri-mf12
    type: manifest
    steps:
      - GET: tp-img11 
      - GET: tp-img12
      - GET: tp-dopts11
      #  applyTo: 
       #   - tp-img12
       
  
      
 # - name: tri-mf13
  #  type: manifest
   # steps:
    #  - GET: tp-img11
    #  - GET: tp-dopts11
    
 # - name: tri-mf14tomf13
  #  type: manifest
   # steps:
    #  - GET: tri-mf12
     
      
  - name: tri-deploy
    type: tripubDeploy
    steps:
      - GET: tri-mf11
      - GET: tp-cluster
      
  - name: tri-deploy12
    type: tripubDeploy
    steps:
      - GET: tri-mf12
      - GET: tp-cluster
      
  #- name: tri-deploytest
   # type: tripubDeploy
    #steps:
     # - GET: tri-mf15tomf13
      #- GET: tp-cluster
      
  #- name: tri-deploy2override
   # type: tripubDeploy
    #steps:
     # - GET: tri-mf13
      #- GET: tp-cluster
      #- GET: tp-dopts12
  
  #- name: tri-ecsdeploy
   # type: ecsDeploy
    #steps:
     # - GET: tri-mf13
     # - GET: tp-ecscluster
      
  #- name: multimf-tpdeploy
   # type: tripubDeploy
    #steps:
     # - GET: tri-mf13
      #- GET: tri-mf11
      #- GET: tp-cluster
      
  #- name: tri-ecstotpdeploy
   # type: tripubDeploy
    #steps:
     # - GET: tri-ecsdeploy
      #- GET: tp-cluster
