jobs:
  - name: vr-man4
    type: manifest
    steps:
      - GET: vr-img2
      
  - name: vr-man5
    type: manifest
    steps:
      - GET: vr-img1
      
 # - name: vr-release3
  #  type: release
   # options:
    #  action: patch
    #steps:
     # - GET: vr-version2
      #- GET: vr-man3
      #- GET: vr-man4
      
  #- name: vr-release4
   # type: release
    #options:
     # action: patch
    #steps:
     # - GET: vr-man3
      #- GET: vr-version3
      
      
#  - name: vr-tpdeploy
 #   type: tripubDeploy
  #  steps:
   #   - GET: vr-man1
    #  - GET: vr-tpcluster
  
