jobs:
  - name: repo-manifest5
    type: manifest
    steps:
      - GET: repo-img1
      - GET: repo-img2
      - GET: repo-img3
      - GET: repo-params1
        applyTo:
          - repo-img1
       #   - repo-img2
      - GET: repo-dopts2
        applyTo:
          - repo-img2
         # - repo-img3
     # - GET: repo-replicas1
      
  - name: repo-ecsdeploy2
    type: ecsDeploy
    steps:
      - GET: repo-manifest5
      - GET: repo-ecscluster1
      
  #- name: multimanifest-dcldeploy
   # type: dclDeploy
    #steps:
     # - GET: repo-manifest
      #- GET: repo-manifest2
      #- GET: repo-dclcluster
