jobs:
  - name: vr-man3
    type: manifest
    steps:
      - GET: vr-img1
      
  - name: vr-man4
    type: manifest
    steps:
      - GET: vr-img2
      
  - name: vr-release3
    type: release
    options:
      action: patch
    steps:
      - GET: vr-version
      - GET: vr-man3
      - GET: vr-man4
      
  - name: vr-release4
    type: release
    options:
      action: patch
    steps:
      - GET: vr-man3
      - GET: vr-version1
      
      
#  - name: vr-tpdeploy
 #   type: tripubDeploy
  #  steps:
   #   - GET: vr-man1
    #  - GET: vr-tpcluster
  
