jobs:
  - name: vr-man5
    type: manifest
    steps:
      - GET: vr-img2
      
  - name: vr-man6
    type: manifest
    steps:
      - GET: vr-img1
      
  - name: vr-release3
    type: release
    options:
      action: patch
    steps:
      - GET: vr-version2
      - GET: vr-man5
      #- GET: vr-man4
      
  - name: vr-release4
    type: release
    options:
      action: alpha
    steps:
      - GET: vr-man6
      - GET: vr-version3
      
      
#  - name: vr-tpdeploy
 #   type: tripubDeploy
  #  steps:
   #   - GET: vr-man1
    #  - GET: vr-tpcluster
  
