jobs:
  - name: repo-manifest6
    type: manifest
    steps:
      - GET: repo-img1
      - GET: repo-img2
      - GET: repo-img3
      - GET: repo-params1
        applyTo:
          - repo-img1
      - GET: repo-dopts2
        applyTo:
          - repo-img2
      - GET: repo-manifest7
  
  - name: repo-manifest7
    type: manifest
    steps:
      - GET: repo-img1
      - GET: repo-replicas2
        applyTo:
          - repo-manifest7
      
  - name: repo-ecsdeploy3
    type: ecsDeploy
    steps:
      - GET: repo-manifest6
      - GET: repo-ecscluster1
      
  #- name: multimanifest-dcldeploy
   # type: dclDeploy
    #steps:
     # - GET: repo-manifest
      #- GET: repo-manifest2
      #- GET: repo-dclcluster
