jobs:
  - name: r6115a-manifest
    type: manifest
    steps:
      - GET: r6115b-image
      #- GET: r6115b-param
      - GET: r6115a-dopt
     
      
  - name: r6115b-manifest
    type: manifest
    steps:
      - GET: r6115c-img6115
      - GET: r6115a-param
      - GET: r6115c-dopt
      - GET: r6115b-replica
     
  - name: r6115d-ecsdeploy
    type: ecsDeploy
    steps:
      - GET: r6115b-manifest
      - GET: r6115-ecscluster
    
#  - name: repo-dcldeploy6115
 #   type: dclDeploy
  #  steps:
   #   - GET: repo-manifest
    #  - GET: repo-dclcluster
     # - GET: repo-replica1
    
#  - name: repo-ecsdeploytodcldeploy6115
 #   type: dclDeploy
  #  steps:
   #   - GET: repo-ecsdeploy
    #  - GET: repo-dclcluster
      
#  - name: multimanifest-dcldeploy
 #   type: dclDeploy
  #  steps:
   #   - GET: repo-manifest
     # - GET: repo-manifest2
    #  - GET: repo-dclcluster
      
  - name: r6115a-ecsdeploy
    type: ecsDeploy
    options: 
      deployMethod: blueGreen # if this property doesn't exist, 'blueGreen' will be the default
    steps:
      - GET: r6115a-manifest
      - GET: r6115-ecscluster
      
  - name: r6115b-ecsdeploy
    type: ecsDeploy
    options: 
      deployMethod: upgrade # if this property doesn't exist, 'blueGreen' will be the default
    steps:
      - GET: r6115a-manifest
      - GET: r6115-ecscluster
      
  - name: r6115c-ecsdeploy
    type: ecsDeploy
    options: 
      deployMethod: blueGreen # if this property doesn't exist, 'blueGreen' will be the default
    steps:
      - GET: r6115a-manifest
      - GET: r6115-ecscluster
      
  - name: r6115e-ecsdeploy
    type: ecsDeploy
    options: 
      #deployMethod: blueGreen # if this property doesn't exist, 'blueGreen' will be the default
    steps:
      - GET: r6115a-manifest
      - GET: r6115-ecscluster
      
  - name: r6115f-ecsdeploy
    type: ecsDeploy
    options: 
      deployMethod: #blueGreen # if this property doesn't exist, 'blueGreen' will be the default
    steps:
      - GET: r6115a-manifest
      - GET: r6115-ecscluster
