jobs:
  - name: r6115a-manifest
    type: manifest
    steps:
      - GET: r6115b-image
      #- GET: r6115b-param
      - GET: r6115a-dopt
     
      
 # - name: repo-manifest2-6115
  #  type: manifest
   # steps:
    #  - GET: repo-image2
     # - GET: repo-param2
     # - GET: repo-doption2
     
 # - name: repo-ecsdeploy6115
  #  type: ecsDeploy
   # steps:
    #  - GET: repo-manifest2
     # - GET: repo-ecscluster
    
#  - name: repo-dcldeploy6115
 #   type: dclDeploy
  #  steps:
   #   - GET: repo-manifest
    #  - GET: repo-dclcluster
     # - GET: repo-replica1
    
#  - name: repo-ecsdeploytodcldeploy6115
 #   type: dclDeploy
  #  steps:
   #   - GET: repo-ecsdeploy
    #  - GET: repo-dclcluster
      
#  - name: multimanifest-dcldeploy
 #   type: dclDeploy
  #  steps:
   #   - GET: repo-manifest
     # - GET: repo-manifest2
    #  - GET: repo-dclcluster
      
  - name: r6115a-ecsdeploy
    type: ecsDeploy
    options: 
      deployMethod: blueGreen # if this property doesn't exist, 'blueGreen' will be the default
    steps:
      - GET: r6115a-manifest
      - GET: r6115-ecscluster
