jobs:
  - name: tp-mf1
    type: manifest
    steps:
      - GET: tp-img1 
      
 # - name: tp-deploy
  #  type: tripubDeploy
   # steps:
     # - GET: tp-mf1
      #- GET: tp-cluster
  
  #- name: tp-ecsdeploy3
   # type: ecsDeploy
    #steps:
     # - GET: repo-manifest6
      #- GET: repo-manifest7
      #- GET: repo-ecscluster1
      
  #- name: multimanifest-dcldeploy
   # type: dclDeploy
    #steps:
     # - GET: repo-manifest
      #- GET: repo-manifest2
      #- GET: repo-dclcluster
